// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1rfBdSH5RkGMmKGxQ-u7RVNTFX3LQJnk',
    appId: '1:322718004770:web:27d7d02aaa08db08b47c7b',
    messagingSenderId: '322718004770',
    projectId: 'portugoose-60053',
    authDomain: 'portugoose-60053.firebaseapp.com',
    databaseURL: 'https://portugoose-60053-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'portugoose-60053.appspot.com',
    measurementId: 'G-RKCX0WDXSC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrZ3zyYtvIsET3RrgHLbc1Xl_QaR-pM14',
    appId: '1:322718004770:android:659cb646c9de5b98b47c7b',
    messagingSenderId: '322718004770',
    projectId: 'portugoose-60053',
    databaseURL: 'https://portugoose-60053-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'portugoose-60053.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP5kXjqqLyjQCxMPiDZeCTSQxMiUqWdiI',
    appId: '1:322718004770:ios:61e521606324464cb47c7b',
    messagingSenderId: '322718004770',
    projectId: 'portugoose-60053',
    databaseURL: 'https://portugoose-60053-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'portugoose-60053.appspot.com',
    iosClientId: '322718004770-542k15hpi0g17c591l87pd779o69587v.apps.googleusercontent.com',
    iosBundleId: 'bear.octo.portugoose',
  );
}
